site_name: srs-deka-llm
site_description: SRS Deka LLM Feature Enhancement: Alerting, Coin Dashboard, Coin Voucher

nav:
  - Home: index.md
  - Introduction: 
      - Purpose of the Document: introduction/purpose-of-the-document.md
  - Description:
      - Product Overview: description/product-overview.md
      - Product Features: description/product-features.md
      - User Documentation: description/documentation.md
  - Interface Requirement:
      - Communication Interface: interface-requirement/communication-interface.md
      - Software Interface: interface-requirement/software-interface.md
  - Functional Requirement:
      - Functional Requirement Table: functional-requirement/functional-requirement-table.md
      - Useradmin and Superadmin Use Case: functional-requirement/useradmin-and-superadmin-use-case.md
      - Charging and Billing: functional-requirement/charging-and-billing.md
      - Monitoring: functional-requirement/monitoring.md
  - Development Timeline:
      - Development Timeline: development-timeline/development-timeline.md
  - Non-Functional Requirements:
      - Non-Functional Requirements: non-functional-requirements/non-functional-requirements.md
  - Appendix:
      - Appendix: appendix/appendix.md

theme:
  name: material

plugins:
  - techdocs-core
  - search

markdown_extensions:
  - admonition
  - pymdownx.details
  - pymdownx.superfences:
      custom_fences:
        - name: mermaid
          class: mermaid
          format: !!python/name:pymdownx.superfences.fence_code_format
  - pymdownx.highlight:
      anchor_linenums: true
  - attr_list
  - md_in_html

extra_css:
  - stylesheets/extra.css 
